version: '3.3'
services:
  postgres:
    container_name: tst-postgres
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5422:5432
  jenkins:
    container_name: tst-jenkins
    restart: always
    image: jenkins/jenkins:lts
    ports:
      - 8070:8080
    volumes:
      - tst-jenkins-home:/var/tst/jenkins_home
volumes:
  tst-jenkins-home:
